Algoritmo "60%"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/08/2024
Var
a: inteiro


Inicio
escreval("Digite um numero inteiro: ")
leia(a)
escreval("A representação de 60% do seu numero é: ",a *(60/100))

Fimalgoritmo