Algoritmo "Soma + 45%"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/08/2024
Var
a,b: inteiro

Inicio
escreval("Digite dois valores inteiros: ")
leia(a,b)
escreval("A soma dos dois numeros escolhidos é: ", a+b, "já a representação de 45% da soma dos numeros é: ",(a+b)*(45/100))



Fimalgoritmo