Algoritmo "Soma e subtração"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/08/2024
Var
a,b,c: inteiro
d: inteiro


Inicio
escreval("Digite 3 valores numericos inteiros ")
leia(a,c,b)
d <- a+c-b
escreval("A soma do primeiro e do terceiro termo, menos o segundo é: ",d)


Fimalgoritmo