Algoritmo "Exercico 10 "
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 09/08/2024
Var
a,l,c: inteiro
z:real


Inicio
escreval("Digite 3 numeros: ")
leia(l,a,c)
z <- (l+a*2)/c
escreval("A soma do primeiro e do segundo termo multiplcado 2 e divido pelo terceiro termo é ",z)



Fimalgoritmo